config/routes.rb
Quiz::Application.routes.draw do

  root 'cats#index'

  resources :cats
  

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
	def index
		@cats = Cat.all
	end

	def new
		@cat = Cat.new
	end

	def create
		Cat.create(cat_params)
		redirect_to root_path
	end

	private

	def cat_params
		params.require(:cat).permit(:name, :description, :birthday)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/index.html.erb
<li>
	<%= link_to 'Add a New Cat', new_cat_path %>
</li>
<%= @cats.each do |cat| %>
	<div>
		<h1>Name: <%= cat.name %><h1><br />
		<i>Description: <%= cat.description %></i><br/>
		<p>Birthday: <%= cat.birthday %></p><br/>
	</div>

	<hr />

<% end %>

app/views/cats/new.html.erb
<h1>Enter details about your cat</h1>
<%= simple_form_for @cat do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :birthday %>
    <br/>
    <%= f.submit 'Create', :class => 'btn btn-primary' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>